name: TITANIUM APK MASTER BUILD
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest # GitHub-ın ən yeni serveri
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install --user buildozer cython virtualenv

      - name: Build with Buildozer (The 2026 Strategy)
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Bütün suallara 'yes' deyərək lisenziyaları keçirik
          yes | buildozer -v android debug
        continue-on-error: false

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Titanium-Nexus-v1
          path: bin/*.apk
          
